const page = (body: string, title = 'Afterglow Sessions — Inttegro × Express') => `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#08091d">
<title>${title}</title><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/checkout-presentations.css"><script type="module" src="/checkout-presentations.js"></script><script src="/demo-ui.js" defer></script></head><body>${body}</body></html>`;

const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, (character) => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;',
})[character] || character);

export function homePage(attemptId: string, error?: { code: string; message: string }) {
  const alert = error?.code === 'configuration_error'
    ? `<section class="setup-card has-config-error" role="status"><span class="setup-kicker">Setup required</span><h3>Connect this copy to Inttegro</h3><p>Add <code>INTTEGRO_API_KEY</code> as a server-side secret, set the active Product and Price IDs plus this deployment’s public URL, then redeploy. The key never belongs in browser JavaScript.</p><div class="setup-actions"><a href="https://studio.inttegro.com/keys">Create an API key</a><a href="https://github.com/zebodotdev/inttegro-demos/blob/express-v1.8.0/express/README.md#deploy-your-own">Deployment guide</a></div></section>`
    : error
      ? `<p class="inline-error" role="alert"><strong>${escapeHtml(error.code.replaceAll('_', ' '))}:</strong> ${escapeHtml(error.message)}</p>`
      : '';
  return page(`<div class="story-event story-event-poster">
    <header class="site-header event-header"><a class="brand event-brand" href="#top" aria-label="Afterglow Sessions home"><span class="brand-mark" aria-hidden="true">A/08</span><span class="event-brand-lockup"><strong>Afterglow</strong><small>Accra sessions</small></span></a><nav class="header-nav" aria-label="Event navigation"><a href="#lineup">Lineup</a><a href="#venue">Venue</a><a class="header-action" href="#tickets">Get tickets <span aria-hidden="true">↘</span></a></nav></header>
    <main id="top"><section class="event-hero event-poster" aria-labelledby="event-title"><img class="event-hero-image" src="/accra-afterglow.jpg" alt="An intimate outdoor concert glowing under amber stage lights"><div class="poster-wash" aria-hidden="true"></div><div class="poster-orbit poster-orbit-one" aria-hidden="true"></div><div class="poster-orbit poster-orbit-two" aria-hidden="true"></div><div class="event-hero-content poster-hero-content"><div class="poster-copy"><p class="event-kicker"><span class="status-dot" aria-hidden="true"></span> One night only · Accra</p><h1 id="event-title"><span class="sr-only">Afterglow</span><span class="poster-title-line poster-title-line-top" aria-hidden="true">After</span><span class="poster-title-line poster-title-line-bottom" aria-hidden="true">glow<span class="poster-period">.</span></span></h1><p class="poster-deck">Three live sets. One open-air courtyard. Music close enough to feel every note.</p></div><aside class="date-card poster-date" aria-label="Saturday 19 September 2026"><span>Sep</span><strong>19</strong><small>Saturday · 2026</small></aside><div class="event-meta event-facts"><div><span>Doors</span><strong>18:30 — late</strong></div><div><span>Place</span><strong>The Observatory</strong></div><div><span>Sound</span><strong>Soul · alté · jazz</strong></div></div><p class="poster-edition" aria-hidden="true">VOL. 08 / ACC</p></div></section>
    <div class="event-marquee" aria-hidden="true"><div class="event-marquee-track"><span>Amaara</span><i>✦</i><span>SuperJazzClub</span><i>✦</i><span>Kojo’s Late Set</span><i>✦</i><span>Amaara</span><i>✦</i><span>SuperJazzClub</span><i>✦</i><span>Kojo’s Late Set</span><i>✦</i></div></div>
    <section class="event-body event-program"><article class="event-intro"><header class="program-heading"><p class="eyebrow">The programme · 19.09.26</p><h2>Music made for the room you’re in.</h2><p>Afterglow brings new voices and close listeners together in a courtyard built for warm sound. No giant screens, no distant stage—just a thoughtful lineup, food from local kitchens, and a night that unfolds at its own pace.</p></header><div id="lineup" class="lineup poster-lineup" aria-label="Event lineup"><div class="lineup-row"><time datetime="2026-09-19T18:30">18:30</time><div class="lineup-act"><strong>Courtyard opens</strong><span>Food and vinyl selections</span></div><span class="lineup-tag">Welcome</span></div><div class="lineup-row lineup-row-featured"><time datetime="2026-09-19T20:00">20:00</time><div class="lineup-act"><strong>Amaara</strong><span>Live soul quartet</span></div><span class="lineup-tag">Live</span></div><div class="lineup-row lineup-row-featured"><time datetime="2026-09-19T21:15">21:15</time><div class="lineup-act"><strong>SuperJazzClub</strong><span>Alté collective set</span></div><span class="lineup-tag">Live</span></div><div class="lineup-row lineup-row-featured"><time datetime="2026-09-19T22:30">22:30</time><div class="lineup-act"><strong>Kojo’s Late Set</strong><span>Jazz and highlife</span></div><span class="lineup-tag">Live</span></div></div><section id="venue" class="venue-panel" aria-labelledby="venue-title"><figure class="venue-visual"><img src="/afterglow-crowd.jpg" alt="A close crowd enjoying an amber-lit performance in the courtyard"><figcaption>From the courtyard · Volume 07</figcaption></figure><div class="venue-copy"><p class="eyebrow">Cantonments · Accra</p><h3 id="venue-title">The Observatory courtyard</h3><p>An open-air room for close listening, with step-free entry and food by three neighbourhood kitchens.</p><dl class="venue-facts"><div><dt>Capacity</dt><dd>180 guests</dd></div><div><dt>Access</dt><dd>Step-free</dd></div><div><dt>Weather</dt><dd>Rain cover</dd></div></dl></div></section></article>
    <aside id="tickets" class="ticket-card poster-ticket" aria-labelledby="ticket-title"><div class="ticket-stub"><span>AG–019</span><span>Accra · GH</span></div><div class="ticket-card-head"><p class="eyebrow">Courtyard admission</p><h2 id="ticket-title">Join us after dark.</h2><p class="microcopy">General admission for one guest. Doors open at 6:30 PM.</p></div><div class="ticket-price-lockup"><span>Admit one</span><p class="ticket-price"><small>GHS</small> 50</p></div><dl class="ticket-detail"><div><dt>Date</dt><dd>19 Sep, 2026</dd></div><div><dt>Entry</dt><dd>1 guest</dd></div><div><dt>Delivery</dt><dd>Email ticket</dd></div></dl><p class="ticket-availability"><span class="status-dot" aria-hidden="true"></span> Courtyard release now available</p>${alert}<form class="checkout-form poster-checkout-form" action="/checkout" method="post" data-checkout-form><input type="hidden" name="attempt_id" value="${attemptId}"><div class="field-grid"><label>Guest name<input name="name" value="Akua Mensah" autocomplete="name" required></label><label>Email address<input type="email" name="email" value="akua@example.com" autocomplete="email" required></label></div><label>Phone number<input type="tel" name="phone" value="+233544998605" autocomplete="tel" required></label><button class="checkout-button" type="submit">Reserve my ticket <span>→</span></button><p class="secure-note">Secure checkout powered by Inttegro</p></form></aside></section></main>
  </div>`);
}

export function resultPage(kind: 'complete' | 'cancel') {
  const complete = kind === 'complete';
  return page(`<main class="story-event story-event-poster result-page event-result-page"><div class="result-orbit" aria-hidden="true"></div><section class="result-card event-result-card"><div class="event-result-brand"><span class="brand-mark" aria-hidden="true">A/08</span><span>Afterglow Sessions</span></div><span class="result-mark">${complete ? '✓' : '←'}</span><p class="eyebrow">${complete ? 'Reservation received' : 'Reservation paused'}</p><h1>${complete ? 'Your night is nearly confirmed.' : 'Your place wasn’t charged.'}</h1><p>${complete ? 'Afterglow will issue the ticket only after the server verifies authoritative payment status.' : 'No completion was claimed. Return to reserve a place whenever you are ready.'}</p><dl class="event-result-meta"><div><dt>Date</dt><dd>19 Sep, 2026</dd></div><div><dt>Venue</dt><dd>The Observatory</dd></div></dl><a class="primary-action" href="/">${complete ? 'Back to Afterglow' : 'Choose a ticket'}</a><span class="result-edition" aria-hidden="true">VOL. 08 / ACC</span></section></main>`, complete ? 'Reservation received' : 'Reservation paused');
}
