server:
  port: ${PORT:3008}
  forward-headers-strategy: framework
spring:
  application:
    name: inttegro-demo-spring-boot
  thymeleaf:
    cache: false
inttegro:
  demo-public-url: ${INTTEGRO_DEMO_PUBLIC_URL:}
