type HomeProps = {
  attemptId: string;
  error?: { code: string; message: string };
};

function Mark() {
  return <svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16 27V13m0 6c-4.8 0-8-2.7-8-7.5 4.8 0 8 2.7 8 7.5Zm0-3.5c4.8 0 8-2.7 8-7.5-4.8 0-8 2.7-8 7.5Z" /></svg>;
}

function SetupMessage({ error }: { error?: HomeProps['error'] }) {
  if (!error) return null;
  if (error.code === 'configuration_error') {
    return <section className="setup-card" role="status"><span>Setup required</span><strong>Connect this copy to Inttegro</strong><p>Add the API key, campaign Product and Price IDs, and public URL as Worker secrets. No credential belongs in this component.</p><div><a href="https://studio.inttegro.com/keys">Create an API key</a><a href="https://github.com/zebodotdev/inttegro-demos/tree/main/redwoodsdk">Read the guide</a></div></section>;
  }
  return <p className="inline-error" role="alert"><strong>{error.code.replaceAll('_', ' ')}:</strong> {error.message}</p>;
}

export function Home({ attemptId, error }: HomeProps) {
  return <div className="campaign-shell">
    <header className="site-header"><a className="brand" href="#top" aria-label="Openfield home"><Mark /><span>openfield</span></a><nav aria-label="Campaign navigation"><a href="#story">Story</a><a href="#plan">The plan</a><a href="#updates">Updates</a><a className="nav-action" href="#support">Back this garden</a></nav></header>
    <main id="top">
      <section className="hero"><div className="hero-copy"><p className="kicker">Riverbend neighborhood · Accra</p><h1>A garden built for every curious mind.</h1><p className="lede">Help turn an overlooked courtyard into a living classroom—where children can grow food, learn outdoors, and gather with the people who call this place home.</p><div className="organizer"><span className="organizer-mark">RF</span><p><strong>Riverbend Foundation</strong><small>Community-led project · Identity verified</small></p><span className="verified" aria-label="Verified organizer">✓</span></div></div><figure className="hero-image"><img src="/openfield-garden.jpg" alt="Neighbors building timber planters in the future Riverbend learning garden" /><figcaption><span>Week three</span> The first six growing beds are already taking root.</figcaption></figure></section>
      <section className="campaign-grid">
        <article className="campaign-story" id="story">
          <div className="chapter"><p className="chapter-number">01 / The story</p><h2>An empty courtyard can become a place that keeps giving.</h2><p>Behind Riverbend Library is a sunlit courtyard that has been closed for more than a decade. Families pass it every day. Teachers see a science room without walls. Neighbors see somewhere to grow herbs, share meals, and slow down together.</p><p>This campaign funds a safe, accessible learning garden with twelve growing beds, a rainwater system, shaded workshop tables, and a small greenhouse maintained by local volunteers.</p><blockquote>“Children understand a seed differently when they are the ones who put it in the soil.”<cite>— Ama Nartey, project lead</cite></blockquote></div>
          <div className="chapter" id="plan"><p className="chapter-number">02 / Where the money goes</p><div className="chapter-heading"><h2>A practical plan, in public.</h2><p>Every contribution is assigned to the build. Updates and receipts are published as each milestone is completed.</p></div><div className="budget" aria-label="Project budget allocation"><div><span><strong>42%</strong> Site and accessible paths</span><i style={{ '--share': '42%' } as React.CSSProperties} /></div><div><span><strong>31%</strong> Beds, soil, and planting</span><i style={{ '--share': '31%' } as React.CSSProperties} /></div><div><span><strong>17%</strong> Rainwater and greenhouse</span><i style={{ '--share': '17%' } as React.CSSProperties} /></div><div><span><strong>10%</strong> Workshops and maintenance</span><i style={{ '--share': '10%' } as React.CSSProperties} /></div></div></div>
          <div className="chapter" id="updates"><p className="chapter-number">03 / Field notes</p><h2>Progress you can follow.</h2><div className="updates"><article><time dateTime="2026-08-31">31 Aug</time><span>Build</span><h3>The first growing beds are in</h3><p>Six locally built timber beds are assembled and the accessible path has been marked out.</p></article><article><time dateTime="2026-08-18">18 Aug</time><span>Community</span><h3>Forty hands, one courtyard</h3><p>Our first volunteer day cleared the site and preserved three mature shade trees.</p></article></div></div>
        </article>
        <aside className="support-card" id="support" aria-labelledby="support-title"><div className="funding"><div><span className="live-dot" /> Flexible funding · 18 days left</div><strong>GHS 182,450</strong><p>raised of GHS 250,000</p><div className="progress" role="progressbar" aria-label="Campaign funding" aria-valuemin={0} aria-valuemax={250000} aria-valuenow={182450}><i /></div><dl><div><dt>624</dt><dd>supporters</dd></div><div><dt>73%</dt><dd>funded</dd></div><div><dt>3</dt><dd>updates</dd></div></dl></div><div className="support-form"><p className="chapter-number">Make a contribution</p><h2 id="support-title">Choose how you’ll help it grow.</h2><SetupMessage error={error} /><form action="/checkout" method="post" data-contribution-form><input type="hidden" name="attempt_id" value={attemptId} /><fieldset><legend className="sr-only">Contribution amount</legend><label className="tier"><input type="radio" name="tier" value="seed" defaultChecked /><span><strong>GHS 50</strong><small>Seed the garden</small></span><i>One contribution unit</i></label><label className="tier"><input type="radio" name="tier" value="grower" /><span><strong>GHS 100</strong><small>Help it grow</small></span><i>Two contribution units</i></label><label className="tier"><input type="radio" name="tier" value="steward" /><span><strong>GHS 250</strong><small>Become a steward</small></span><i>Five contribution units</i></label></fieldset><div className="fields"><label>Full name<input name="name" defaultValue="Akua Mensah" autoComplete="name" required /></label><label>Email address<input type="email" name="email" defaultValue="akua@example.com" autoComplete="email" required /></label><label>Phone number<input type="tel" name="phone" defaultValue="+233544998605" autoComplete="tel" inputMode="tel" required /></label></div><button type="submit"><span>Contribute GHS 50</span><svg viewBox="0 0 20 20" aria-hidden="true"><path d="m7 4 6 6-6 6" /></svg></button><p className="secure-note"><span aria-hidden="true">◇</span> Secure checkout powered by Inttegro</p></form></div><footer><p>Openfield collects immediate contributions for this flexible-funding campaign. Contributions are not represented as tax-deductible gifts.</p></footer></aside>
      </section>
      <p className="demo-disclosure">Openfield and Riverbend Foundation are fictional demonstration entities.</p>
    </main>
  </div>;
}
