type HomeProps = {
  attemptId: string;
  error?: { code: string; message: string };
};

function Mark() {
  return <svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16 27V13m0 6c-4.8 0-8-2.7-8-7.5 4.8 0 8 2.7 8 7.5Zm0-3.5c4.8 0 8-2.7 8-7.5-4.8 0-8 2.7-8 7.5Z" /></svg>;
}

function SetupMessage({ error }: { error?: HomeProps['error'] }) {
  if (!error) return null;
  if (error.code === 'configuration_error') {
    return <section className="setup-card" role="status"><span>Setup required</span><strong>Connect this copy to Inttegro</strong><p>Add the API key, campaign Product and Price IDs, and public URL as Worker secrets. No credential belongs in this component.</p><div><a href="https://studio.inttegro.com/keys">Create an API key</a><a href="https://github.com/zebodotdev/inttegro-demos/tree/main/redwoodsdk">Read the guide</a></div></section>;
  }
  return <p className="inline-error" role="alert"><strong>{error.code.replaceAll('_', ' ')}:</strong> {error.message}</p>;
}

export function Home({ attemptId, error }: HomeProps) {
  return <div className="campaign-shell">
    <header className="site-header"><a className="brand" href="#top" aria-label="Openfield home"><Mark /><span>openfield</span></a><nav aria-label="Campaign navigation"><a href="#story">Story</a><a href="#impact">Impact</a><a href="#plan">The plan</a><a href="#updates">Field notes</a><a className="nav-action" href="#support">Back this garden</a></nav></header>
    <main id="top">
      <section className="hero">
	<div className="hero-copy"><div className="hero-dateline"><p className="kicker">Riverbend neighborhood · Accra</p><span>Community verified</span></div><h1>Give a courtyard back to its children.</h1><p className="lede">Together, we can turn an overlooked patch of concrete into a living classroom—where 120 young people can grow food, learn outdoors, and gather with the community around them.</p><div className="organizer"><span className="organizer-mark">RF</span><p><strong>Riverbend Foundation</strong><small>Community-led since 2019 · Identity verified</small></p><span className="verified" aria-label="Verified organizer">✓</span></div></div>
	<figure className="hero-image"><img src="/openfield-garden.jpg" alt="Neighbors building timber planters in the future Riverbend learning garden" /><figcaption><span>Field note · Week three</span> Volunteers built the first six growing beds while preserving the courtyard’s three mature shade trees.</figcaption></figure>
      </section>

      <section className="impact-strip" id="impact" aria-labelledby="impact-title">
	<header><p className="chapter-number">The difference this garden makes</p><h2 id="impact-title">A small plot. A lasting place to learn.</h2></header>
	<dl><div><dt>120</dt><dd>young learners welcomed every week</dd></div><div><dt>12</dt><dd>accessible growing beds planned</dd></div><div><dt>8,000 L</dt><dd>of rainwater storage capacity</dd></div><div><dt>40</dt><dd>neighbors already volunteering</dd></div></dl>
	<figure className="impact-field-image"><img src="/openfield-impact.jpg" alt="A teacher and four children planting vegetables in a thriving community garden" /><figcaption><span>What comes next</span> Weekly garden sessions will connect science lessons to soil, food, and patient care.</figcaption></figure>
	<p className="impact-method"><span aria-hidden="true">↗</span><span><strong>Measured in public.</strong> Build receipts, milestone evidence, and field updates are published throughout the project.</span></p>
      </section>

      <section className="campaign-grid">
	<article className="campaign-story" id="story">
	  <div className="chapter story-chapter"><p className="chapter-number">01 / Why this place</p><h2>An empty courtyard can become something that keeps giving.</h2><p className="story-lead">Behind Riverbend Library is a sunlit courtyard that has been closed for more than a decade. Families pass it every day. Teachers see a science room without walls. Neighbors see somewhere to grow herbs, share meals, and slow down together.</p><p>This campaign funds a safe, accessible learning garden with twelve growing beds, a rainwater system, shaded workshop tables, and a small greenhouse maintained by local volunteers.</p><blockquote className="human-quote"><span aria-hidden="true">“</span><p>Children understand a seed differently when they are the ones who put it in the soil.</p><cite><strong>Ama Nartey</strong><small>Project lead and Riverbend science teacher</small></cite></blockquote></div>

	  <section className="field-evidence" aria-labelledby="evidence-title"><div className="chapter-heading"><div><p className="chapter-number">Proof from the field</p><h2 id="evidence-title">Built with the neighborhood, not just for it.</h2></div><p>Each claim is paired with a practical record that supporters can revisit as the work moves forward.</p></div><div className="evidence-grid"><article><span className="evidence-mark" aria-hidden="true">01</span><p className="evidence-state">Verified · 12 Aug</p><h3>Courtyard access secured</h3><p>Riverbend Library approved community use of the site through 2031.</p><small>Library stewardship agreement</small></article><article><span className="evidence-mark" aria-hidden="true">02</span><p className="evidence-state">Published · 20 Aug</p><h3>Accessible plan reviewed</h3><p>Local families and two mobility advocates reviewed the path and bed layout.</p><small>Annotated site plan</small></article><article><span className="evidence-mark" aria-hidden="true">03</span><p className="evidence-state">Counted · 31 Aug</p><h3>Six beds installed</h3><p>The first half of the growing beds were built by forty neighborhood volunteers.</p><small>Field count and build log</small></article></div></section>

	  <div className="chapter" id="plan"><p className="chapter-number">02 / The plan</p><div className="chapter-heading"><div><h2>Every cedi has a job.</h2><p>Contributions are assigned to the build. Updates and receipts are published as each milestone is completed.</p></div><p className="plan-total"><span>Working budget</span><strong>GHS 250,000</strong></p></div><div className="budget" aria-label="Project budget allocation"><div><span><strong>42%</strong> Site and accessible paths</span><i style={{ '--share': '42%' } as React.CSSProperties} /></div><div><span><strong>31%</strong> Beds, soil, and planting</span><i style={{ '--share': '31%' } as React.CSSProperties} /></div><div><span><strong>17%</strong> Rainwater and greenhouse</span><i style={{ '--share': '17%' } as React.CSSProperties} /></div><div><span><strong>10%</strong> Workshops and maintenance</span><i style={{ '--share': '10%' } as React.CSSProperties} /></div></div>
	    <ol className="milestone-list" aria-label="Build milestones"><li className="is-complete"><span aria-hidden="true">✓</span><div><p>Site cleared with mature trees protected</p><time dateTime="2026-08-18">Completed 18 Aug</time></div><strong>Complete</strong></li><li className="is-current"><span aria-hidden="true">2</span><div><p>Twelve accessible growing beds</p><small>Six built · six in production</small></div><strong>In progress</strong></li><li><span aria-hidden="true">3</span><div><p>Rainwater system and shaded tables</p><small>Materials reserved</small></div><strong>Up next</strong></li><li><span aria-hidden="true">4</span><div><p>First learner planting workshop</p><time dateTime="2026-10-12">Planned for 12 Oct</time></div><strong>Planned</strong></li></ol>
	  </div>

	  <div className="chapter" id="updates"><p className="chapter-number">03 / Field notes</p><div className="chapter-heading"><div><h2>See the work as it happens.</h2><p>Short, dated accounts from the people doing the work—successes, changes, and setbacks included.</p></div><span className="update-count">3 published</span></div><div className="updates"><article><div className="update-meta"><time dateTime="2026-08-31">31 Aug</time><span>Build</span></div><p className="update-index" aria-hidden="true">03</p><h3>The first growing beds are in</h3><p>Six locally built timber beds are assembled and the accessible path has been marked out.</p><a href="#support" aria-label="Support the project after reading The first growing beds are in">Help fund the next six <span aria-hidden="true">→</span></a></article><article><div className="update-meta"><time dateTime="2026-08-18">18 Aug</time><span>Community</span></div><p className="update-index" aria-hidden="true">02</p><h3>Forty hands, one courtyard</h3><p>Our first volunteer day cleared the site and preserved three mature shade trees.</p><a href="#support" aria-label="Support the project after reading Forty hands, one courtyard">Join the next chapter <span aria-hidden="true">→</span></a></article><article><div className="update-meta"><time dateTime="2026-08-12">12 Aug</time><span>Stewardship</span></div><p className="update-index" aria-hidden="true">01</p><h3>The courtyard is ours to care for</h3><p>Riverbend Library signed the long-term agreement that keeps this space in community hands.</p><a href="#plan" aria-label="Read the Riverbend project plan">See the public plan <span aria-hidden="true">→</span></a></article></div></div>
	</article>

	<aside className="support-card" id="support" aria-labelledby="support-title">
	  <div className="funding"><div className="funding-state"><span><span className="live-dot" /> Community funded</span><span>18 days left</span></div><strong>GHS 182,450</strong><p>raised of GHS 250,000</p><div className="progress" role="progressbar" aria-label="Campaign funding" aria-valuemin={0} aria-valuemax={250000} aria-valuenow={182450}><i /></div><dl><div><dt>624</dt><dd>supporters</dd></div><div><dt>73%</dt><dd>funded</dd></div><div><dt>3</dt><dd>field notes</dd></div></dl></div>
	  <div className="support-impact-promise"><span className="support-impact-mark" aria-hidden="true">✦</span><p><strong>GHS 50 helps stock a growing bed.</strong><span>Seed packs, child-sized tools, and the first planting workshop.</span></p></div>
	  <div className="support-form"><p className="chapter-number">Make a contribution</p><h2 id="support-title">Choose how you’ll help it grow.</h2><SetupMessage error={error} /><form action="/checkout" method="post" data-contribution-form data-checkout-show-line-items="false"><input type="hidden" name="attempt_id" value={attemptId} /><fieldset><legend className="sr-only">Contribution amount</legend><label className="tier"><input type="radio" name="tier" value="seed" defaultChecked /><span><strong>GHS 50</strong><small>Seed the garden</small></span><i>One contribution unit</i></label><label className="tier"><input type="radio" name="tier" value="grower" /><span><strong>GHS 100</strong><small>Help it grow</small></span><i>Two contribution units</i></label><label className="tier"><input type="radio" name="tier" value="steward" /><span><strong>GHS 250</strong><small>Become a steward</small></span><i>Five contribution units</i></label></fieldset><div className="fields"><label>Full name<input name="name" defaultValue="Akua Mensah" autoComplete="name" required /></label><label>Email address<input type="email" name="email" defaultValue="akua@example.com" autoComplete="email" required /></label><label>Phone number<input type="tel" name="phone" defaultValue="+233544998605" autoComplete="tel" inputMode="tel" required /></label></div><button type="submit"><span>Contribute GHS 50</span><svg viewBox="0 0 20 20" aria-hidden="true"><path d="m7 4 6 6-6 6" /></svg></button><p className="secure-note"><span aria-hidden="true">◇</span> Secure checkout powered by Inttegro</p></form></div>
	  <ul className="support-assurances" aria-label="Campaign assurances"><li><span aria-hidden="true">✓</span><p><strong>Verified organizer</strong><small>Identity and community role reviewed</small></p></li><li><span aria-hidden="true">↗</span><p><strong>Public allocation</strong><small>Milestones and receipts stay visible</small></p></li><li><span aria-hidden="true">◎</span><p><strong>Flexible funding</strong><small>Contributions go directly to the build</small></p></li></ul>
	  <footer><p>Openfield collects immediate contributions for this flexible-funding campaign. Contributions are not represented as tax-deductible gifts.</p></footer>
	</aside>
      </section>
      <p className="demo-disclosure">Openfield and Riverbend Foundation are fictional demonstration entities.</p>
    </main>
  </div>;
}
