const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, (character) => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;',
})[character] || character);

const document = (body: string, title = 'Openfield — Riverbend Learning Garden') => `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="theme-color" content="#173b2f"><meta name="description" content="Help turn Riverbend's unused courtyard into a garden for learning, growing, and gathering.">
<title>${title}</title><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/checkout-presentations.css"><script src="/checkout-presentations.js" defer></script><script src="/campaign.js" defer></script></head><body>${body}</body></html>`;

function setupMessage(error?: { code: string; message: string }) {
  if (error?.code === 'configuration_error') {
    return `<section class="setup-card" role="status"><span>Setup required</span><strong>Connect this copy to Inttegro</strong><p>Add the API key, campaign Product and Price IDs, and public URL as server-side environment variables. No secret belongs in this page.</p><div><a href="https://studio.inttegro.com/keys">Create an API key</a><a href="https://github.com/zebodotdev/inttegro-demos/tree/main/nestjs">Read the guide</a></div></section>`;
  }
  return error
    ? `<p class="inline-error" role="alert"><strong>${escapeHtml(error.code.replaceAll('_', ' '))}:</strong> ${escapeHtml(error.message)}</p>`
    : '';
}

export function homePage(attemptId: string, error?: { code: string; message: string }) {
  return document(`<div class="campaign-shell">
  <header class="site-header"><a class="brand" href="#top" aria-label="Openfield home"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16 27V13m0 6c-4.8 0-8-2.7-8-7.5 4.8 0 8 2.7 8 7.5Zm0-3.5c4.8 0 8-2.7 8-7.5-4.8 0-8 2.7-8 7.5Z"/></svg><span>openfield</span></a><nav aria-label="Campaign navigation"><a href="#story">Story</a><a href="#plan">The plan</a><a href="#updates">Updates</a><a class="nav-action" href="#support">Back this garden</a></nav></header>
  <main id="top">
    <section class="hero"><div class="hero-copy"><p class="kicker">Riverbend neighborhood · Accra</p><h1>A garden built for every curious mind.</h1><p class="lede">Help turn an overlooked courtyard into a living classroom—where children can grow food, learn outdoors, and gather with the people who call this place home.</p><div class="organizer"><span class="organizer-mark">RF</span><p><strong>Riverbend Foundation</strong><small>Community-led project · Identity verified</small></p><span class="verified" aria-label="Verified organizer">✓</span></div></div><figure class="hero-image"><img src="/openfield-garden.jpg" alt="Neighbors building timber planters in the future Riverbend learning garden"><figcaption><span>Week three</span> The first six growing beds are already taking root.</figcaption></figure></section>
    <section class="campaign-grid">
      <article class="campaign-story" id="story">
        <div class="chapter"><p class="chapter-number">01 / The story</p><h2>An empty courtyard can become a place that keeps giving.</h2><p>Behind Riverbend Library is a sunlit courtyard that has been closed for more than a decade. Families pass it every day. Teachers see a science room without walls. Neighbors see somewhere to grow herbs, share meals, and slow down together.</p><p>This campaign funds a safe, accessible learning garden with twelve growing beds, a rainwater system, shaded workshop tables, and a small greenhouse maintained by local volunteers.</p><blockquote>“Children understand a seed differently when they are the ones who put it in the soil.”<cite>— Ama Nartey, project lead</cite></blockquote></div>
        <div class="chapter" id="plan"><p class="chapter-number">02 / Where the money goes</p><div class="chapter-heading"><h2>A practical plan, in public.</h2><p>Every contribution is assigned to the build. Updates and receipts are published as each milestone is completed.</p></div><div class="budget" aria-label="Project budget allocation"><div><span><strong>42%</strong> Site and accessible paths</span><i style="--share:42%"></i></div><div><span><strong>31%</strong> Beds, soil, and planting</span><i style="--share:31%"></i></div><div><span><strong>17%</strong> Rainwater and greenhouse</span><i style="--share:17%"></i></div><div><span><strong>10%</strong> Workshops and maintenance</span><i style="--share:10%"></i></div></div></div>
        <div class="chapter" id="updates"><p class="chapter-number">03 / Field notes</p><h2>Progress you can follow.</h2><div class="updates"><article><time datetime="2026-08-31">31 Aug</time><span>Build</span><h3>The first growing beds are in</h3><p>Six locally built timber beds are assembled and the accessible path has been marked out.</p></article><article><time datetime="2026-08-18">18 Aug</time><span>Community</span><h3>Forty hands, one courtyard</h3><p>Our first volunteer day cleared the site and preserved three mature shade trees.</p></article></div></div>
      </article>
      <aside class="support-card" id="support" aria-labelledby="support-title"><div class="funding"><div><span class="live-dot"></span> Flexible funding · 18 days left</div><strong>GHS 182,450</strong><p>raised of GHS 250,000</p><div class="progress" role="progressbar" aria-label="Campaign funding" aria-valuemin="0" aria-valuemax="250000" aria-valuenow="182450"><i></i></div><dl><div><dt>624</dt><dd>supporters</dd></div><div><dt>73%</dt><dd>funded</dd></div><div><dt>3</dt><dd>updates</dd></div></dl></div><div class="support-form"><p class="chapter-number">Make a contribution</p><h2 id="support-title">Choose how you’ll help it grow.</h2>${setupMessage(error)}<form action="/checkout" method="post" data-contribution-form><input type="hidden" name="attempt_id" value="${attemptId}"><fieldset><legend class="sr-only">Contribution amount</legend><label class="tier"><input type="radio" name="tier" value="seed" checked><span><strong>GHS 50</strong><small>Seed the garden</small></span><i>One contribution unit</i></label><label class="tier"><input type="radio" name="tier" value="grower"><span><strong>GHS 100</strong><small>Help it grow</small></span><i>Two contribution units</i></label><label class="tier"><input type="radio" name="tier" value="steward"><span><strong>GHS 250</strong><small>Become a steward</small></span><i>Five contribution units</i></label></fieldset><div class="fields"><label>Full name<input name="name" value="Akua Mensah" autocomplete="name" required></label><label>Email address<input type="email" name="email" value="akua@example.com" autocomplete="email" required></label><label>Phone number<input type="tel" name="phone" value="+233544998605" autocomplete="tel" inputmode="tel" required></label></div><button type="submit"><span>Contribute GHS 50</span><svg viewBox="0 0 20 20" aria-hidden="true"><path d="m7 4 6 6-6 6"/></svg></button><p class="secure-note"><span aria-hidden="true">◇</span> Secure checkout powered by Inttegro</p></form></div><footer><p>Openfield collects immediate contributions for this flexible-funding campaign. Contributions are not represented as tax-deductible gifts.</p></footer></aside>
    </section><p class="demo-disclosure">Openfield and Riverbend Foundation are fictional demonstration entities.</p>
  </main></div>`);
}

export function resultPage(kind: 'complete' | 'cancel' | 'not-found') {
  const content = kind === 'complete'
    ? { eyebrow: 'Contribution received', title: 'You helped something take root.', copy: 'Openfield will count the contribution only after the server verifies authoritative payment status.', action: 'Return to the garden', mark: '✓' }
    : kind === 'cancel'
      ? { eyebrow: 'Checkout paused', title: 'Nothing was charged.', copy: 'The garden will be here when you are ready. Your contribution was not marked as complete.', action: 'Choose a contribution', mark: '←' }
      : { eyebrow: 'Page not found', title: 'This path is still unplanted.', copy: 'Return to the Riverbend campaign to see the project and its latest progress.', action: 'Visit the campaign', mark: '↗' };
  return document(`<main class="result-page"><section><a class="brand" href="/"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16 27V13m0 6c-4.8 0-8-2.7-8-7.5 4.8 0 8 2.7 8 7.5Zm0-3.5c4.8 0 8-2.7 8-7.5-4.8 0-8 2.7-8 7.5Z"/></svg><span>openfield</span></a><span class="result-mark">${content.mark}</span><p class="chapter-number">${content.eyebrow}</p><h1>${content.title}</h1><p>${content.copy}</p><a class="result-action" href="/">${content.action}<span>→</span></a></section></main>`, content.title);
}
