const page = (body: string, title = 'Afterglow Sessions — Inttegro × Express') => `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#08091d">
<title>${title}</title><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/checkout-presentations.css"><script src="/checkout-presentations.js" defer></script><script src="/demo-ui.js" defer></script></head><body>${body}</body></html>`;

const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, (character) => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;',
})[character] || character);

export function homePage(attemptId: string, error?: { code: string; message: string }) {
  const alert = error?.code === 'configuration_error'
    ? `<section class="setup-card has-config-error" role="status"><span class="setup-kicker">Setup required</span><h3>Connect this copy to Inttegro</h3><p>Add <code>INTTEGRO_API_KEY</code> as a server-side secret, set the active Product and Price IDs plus this deployment’s public URL, then redeploy. The key never belongs in browser JavaScript.</p><div class="setup-actions"><a href="https://studio.inttegro.com/keys">Create an API key</a><a href="https://github.com/zebodotdev/inttegro-demos/blob/express-v1.6.2/express/README.md#deploy-your-own">Deployment guide</a></div></section>`
    : error
      ? `<p class="inline-error" role="alert"><strong>${escapeHtml(error.code.replaceAll('_', ' '))}:</strong> ${escapeHtml(error.message)}</p>`
      : '';
  return page(`<div class="story-event">
    <header class="site-header"><a class="brand" href="#top"><span class="brand-mark">A</span>Afterglow</a><nav class="header-nav" aria-label="Event navigation"><a href="#lineup">Lineup</a><a href="#venue">Venue</a><a class="header-action" href="#tickets">Get tickets</a></nav></header>
    <main id="top"><section class="event-hero" aria-labelledby="event-title"><img class="event-hero-image" src="/accra-afterglow.jpg" alt="An intimate outdoor concert glowing under amber stage lights"><div class="event-hero-content"><div><p class="event-kicker"><span class="status-dot"></span> Accra Sessions · Volume 08</p><h1 id="event-title">After<br>glow.</h1><div class="event-meta"><span>◷ 6:30 PM — late</span><span>⌖ The Observatory, Cantonments</span><span>♬ Live soul · alté · jazz</span></div></div><aside class="date-card" aria-label="Saturday 19 September"><strong>19</strong><span>September · Sat</span></aside></div></section>
    <section class="event-body"><div class="event-intro"><p class="eyebrow">One night. Three live sets.</p><h2>Music made for the room you’re in.</h2><p>Afterglow brings new voices and close listeners together in a courtyard built for warm sound. No giant screens, no distant stage—just a thoughtful lineup, food from local kitchens, and a night that unfolds at its own pace.</p><div id="lineup" class="lineup" aria-label="Event lineup"><div class="lineup-row"><time>18:30</time><strong>Courtyard opens</strong><span>Food · vinyl selections</span></div><div class="lineup-row"><time>20:00</time><strong>Amaara</strong><span>Live soul quartet</span></div><div class="lineup-row"><time>21:15</time><strong>SuperJazzClub</strong><span>Alté collective set</span></div><div class="lineup-row"><time>22:30</time><strong>Kojo’s Late Set</strong><span>Jazz · highlife</span></div></div><div id="venue" class="pill-row" style="margin-top:28px"><span class="pill">Outdoor courtyard</span><span class="pill">Accessible entrance</span><span class="pill">Limited to 180 guests</span></div></div>
    <aside id="tickets" class="ticket-card" aria-labelledby="ticket-title"><p class="eyebrow">Courtyard admission</p><h2 id="ticket-title">Your night at Afterglow</h2><p class="microcopy">One general-admission ticket. Doors at 6:30 PM.</p><p class="ticket-price">GHS 50</p><div class="ticket-detail"><div><span>Date</span><strong>19 Sep, 2026</strong></div><div><span>Entry</span><strong>1 guest</strong></div><div><span>Delivery</span><strong>Email ticket</strong></div></div>${alert}<form class="checkout-form" action="/checkout" method="post" data-checkout-form><input type="hidden" name="attempt_id" value="${attemptId}"><div class="field-grid"><label>Guest name<input name="name" value="Akua Mensah" autocomplete="name" required></label><label>Email address<input type="email" name="email" value="akua@example.com" autocomplete="email" required></label></div><label>Phone number<input type="tel" name="phone" value="+233544998605" autocomplete="tel" required></label><button class="checkout-button" type="submit">Reserve my ticket <span>→</span></button><p class="secure-note">Secure checkout powered by Inttegro</p></form></aside></section></main>
  </div>`);
}

export function resultPage(kind: 'complete' | 'cancel') {
  const complete = kind === 'complete';
  return page(`<main class="story-event result-page"><section class="result-card"><span class="result-mark">${complete ? '✓' : '←'}</span><p class="eyebrow">${complete ? 'Reservation received' : 'Reservation paused'}</p><h1>${complete ? 'Your night is nearly confirmed.' : 'Your place wasn’t charged.'}</h1><p>${complete ? 'Afterglow will issue the ticket only after the server verifies authoritative payment status.' : 'No completion was claimed. Return to reserve a place whenever you are ready.'}</p><a class="primary-action" href="/">${complete ? 'Back to Afterglow' : 'Choose a ticket'}</a></section></main>`, complete ? 'Reservation received' : 'Reservation paused');
}
