const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, (character) => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;',
})[character] || character);

// Server-rendering the selector preserves an ordinary hosted-page form when
// JavaScript is absent. The Svelte island reads this value only to choose how
// to present the same server-finalized Inttegro Order.
const checkoutPresentationPicker = `<fieldset class="checkout-presentation-picker">
  <legend>Checkout experience</legend>
  <div class="checkout-presentation-options">
    <label><input type="radio" name="checkout_mode" value="embedded" checked><span><svg viewBox="0 0 20 20" aria-hidden="true"><rect x="2.5" y="3.5" width="15" height="13" rx="2"/><path d="M6 7h8M6 10h5M6 13h3"/></svg><strong>Embedded</strong></span></label>
    <label><input type="radio" name="checkout_mode" value="modal"><span><svg viewBox="0 0 20 20" aria-hidden="true"><rect x="2.5" y="3.5" width="15" height="13" rx="2"/><rect x="5.5" y="6.5" width="9" height="7" rx="1.5"/></svg><strong>Modal</strong></span></label>
    <label><input type="radio" name="checkout_mode" value="hosted"><span><svg viewBox="0 0 20 20" aria-hidden="true"><path d="M8 4H4.5a2 2 0 0 0-2 2v9.5a2 2 0 0 0 2 2H14a2 2 0 0 0 2-2V12"/><path d="M11 2.5h6.5V9M17 3l-8 8"/></svg><strong>Hosted page</strong></span></label>
  </div>
</fieldset>`;

const document = (body: string, title = 'Openfield — Riverbend Learning Garden') => `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="theme-color" content="#173b2f"><meta name="description" content="Help turn Riverbend's unused courtyard into a garden for learning, growing, and gathering.">
<title>${title}</title><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/checkout-presentations.css"><script type="module" src="/svelte/checkout.js"></script><script src="/campaign.js" defer></script></head><body>${body}</body></html>`;

function setupMessage(error?: { code: string; message: string }) {
  if (error?.code === 'configuration_error') {
    return `<section class="setup-card" role="status"><span>Setup required</span><strong>Connect this copy to Inttegro</strong><p>Add the API key, campaign Product and Price IDs, and public URL as server-side environment variables. No secret belongs in this page.</p><div><a href="https://studio.inttegro.com/keys">Create an API key</a><a href="https://github.com/zebodotdev/inttegro-demos/tree/main/nestjs">Read the guide</a></div></section>`;
  }
  return error
    ? `<p class="inline-error" role="alert"><strong>${escapeHtml(error.code.replaceAll('_', ' '))}:</strong> ${escapeHtml(error.message)}</p>`
    : '';
}

export function homePage(attemptId: string, error?: { code: string; message: string }) {
  return document(`<div class="campaign-shell">
  <header class="site-header"><a class="brand" href="#top" aria-label="Openfield home"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16 27V13m0 6c-4.8 0-8-2.7-8-7.5 4.8 0 8 2.7 8 7.5Zm0-3.5c4.8 0 8-2.7 8-7.5-4.8 0-8 2.7-8 7.5Z"/></svg><span>openfield</span></a><nav aria-label="Campaign navigation"><a href="#story">Story</a><a href="#impact">Impact</a><a href="#plan">The plan</a><a href="#updates">Field notes</a><a class="nav-action" href="#support">Back this garden</a></nav></header>
  <main id="top">
    <section class="hero">
      <div class="hero-copy"><div class="hero-dateline"><p class="kicker">Riverbend neighborhood · Accra</p><span>Community verified</span></div><h1>Give a courtyard back to its children.</h1><p class="lede">Together, we can turn an overlooked patch of concrete into a living classroom—where 120 young people can grow food, learn outdoors, and gather with the community around them.</p><div class="organizer"><span class="organizer-mark">RF</span><p><strong>Riverbend Foundation</strong><small>Community-led since 2019 · Identity verified</small></p><span class="verified" aria-label="Verified organizer">✓</span></div></div>
      <figure class="hero-image"><img src="/openfield-garden.jpg" alt="Neighbors building timber planters in the future Riverbend learning garden"><figcaption><span>Field note · Week three</span> Volunteers built the first six growing beds while preserving the courtyard’s three mature shade trees.</figcaption></figure>
    </section>

    <section class="impact-strip" id="impact" aria-labelledby="impact-title">
      <header><p class="chapter-number">The difference this garden makes</p><h2 id="impact-title">A small plot. A lasting place to learn.</h2></header>
      <dl><div><dt>120</dt><dd>young learners welcomed every week</dd></div><div><dt>12</dt><dd>accessible growing beds planned</dd></div><div><dt>8,000 L</dt><dd>of rainwater storage capacity</dd></div><div><dt>40</dt><dd>neighbors already volunteering</dd></div></dl>
      <figure class="impact-field-image"><img src="/openfield-impact.jpg" alt="A teacher and four children planting vegetables in a thriving community garden"><figcaption><span>What comes next</span> Weekly garden sessions will connect science lessons to soil, food, and patient care.</figcaption></figure>
      <p class="impact-method"><span aria-hidden="true">↗</span><span><strong>Measured in public.</strong> Build receipts, milestone evidence, and field updates are published throughout the project.</span></p>
    </section>

    <section class="campaign-grid">
      <article class="campaign-story" id="story">
	<div class="chapter story-chapter"><p class="chapter-number">01 / Why this place</p><h2>An empty courtyard can become something that keeps giving.</h2><p class="story-lead">Behind Riverbend Library is a sunlit courtyard that has been closed for more than a decade. Families pass it every day. Teachers see a science room without walls. Neighbors see somewhere to grow herbs, share meals, and slow down together.</p><p>This campaign funds a safe, accessible learning garden with twelve growing beds, a rainwater system, shaded workshop tables, and a small greenhouse maintained by local volunteers.</p><blockquote class="human-quote"><span aria-hidden="true">“</span><p>Children understand a seed differently when they are the ones who put it in the soil.</p><cite><strong>Ama Nartey</strong><small>Project lead and Riverbend science teacher</small></cite></blockquote></div>

	<section class="field-evidence" aria-labelledby="evidence-title"><div class="chapter-heading"><div><p class="chapter-number">Proof from the field</p><h2 id="evidence-title">Built with the neighborhood, not just for it.</h2></div><p>Each claim is paired with a practical record that supporters can revisit as the work moves forward.</p></div><div class="evidence-grid"><article><span class="evidence-mark" aria-hidden="true">01</span><p class="evidence-state">Verified · 12 Aug</p><h3>Courtyard access secured</h3><p>Riverbend Library approved community use of the site through 2031.</p><small>Library stewardship agreement</small></article><article><span class="evidence-mark" aria-hidden="true">02</span><p class="evidence-state">Published · 20 Aug</p><h3>Accessible plan reviewed</h3><p>Local families and two mobility advocates reviewed the path and bed layout.</p><small>Annotated site plan</small></article><article><span class="evidence-mark" aria-hidden="true">03</span><p class="evidence-state">Counted · 31 Aug</p><h3>Six beds installed</h3><p>The first half of the growing beds were built by forty neighborhood volunteers.</p><small>Field count and build log</small></article></div></section>

	<div class="chapter" id="plan"><p class="chapter-number">02 / The plan</p><div class="chapter-heading"><div><h2>Every cedi has a job.</h2><p>Contributions are assigned to the build. Updates and receipts are published as each milestone is completed.</p></div><p class="plan-total"><span>Working budget</span><strong>GHS 250,000</strong></p></div><div class="budget" aria-label="Project budget allocation"><div><span><strong>42%</strong> Site and accessible paths</span><i style="--share:42%"></i></div><div><span><strong>31%</strong> Beds, soil, and planting</span><i style="--share:31%"></i></div><div><span><strong>17%</strong> Rainwater and greenhouse</span><i style="--share:17%"></i></div><div><span><strong>10%</strong> Workshops and maintenance</span><i style="--share:10%"></i></div></div>
	  <ol class="milestone-list" aria-label="Build milestones"><li class="is-complete"><span aria-hidden="true">✓</span><div><p>Site cleared with mature trees protected</p><time datetime="2026-08-18">Completed 18 Aug</time></div><strong>Complete</strong></li><li class="is-current"><span aria-hidden="true">2</span><div><p>Twelve accessible growing beds</p><small>Six built · six in production</small></div><strong>In progress</strong></li><li><span aria-hidden="true">3</span><div><p>Rainwater system and shaded tables</p><small>Materials reserved</small></div><strong>Up next</strong></li><li><span aria-hidden="true">4</span><div><p>First learner planting workshop</p><time datetime="2026-10-12">Planned for 12 Oct</time></div><strong>Planned</strong></li></ol>
	</div>

	<div class="chapter" id="updates"><p class="chapter-number">03 / Field notes</p><div class="chapter-heading"><div><h2>See the work as it happens.</h2><p>Short, dated accounts from the people doing the work—successes, changes, and setbacks included.</p></div><span class="update-count">3 published</span></div><div class="updates"><article><div class="update-meta"><time datetime="2026-08-31">31 Aug</time><span>Build</span></div><p class="update-index" aria-hidden="true">03</p><h3>The first growing beds are in</h3><p>Six locally built timber beds are assembled and the accessible path has been marked out.</p><a href="#support" aria-label="Support the project after reading The first growing beds are in">Help fund the next six <span aria-hidden="true">→</span></a></article><article><div class="update-meta"><time datetime="2026-08-18">18 Aug</time><span>Community</span></div><p class="update-index" aria-hidden="true">02</p><h3>Forty hands, one courtyard</h3><p>Our first volunteer day cleared the site and preserved three mature shade trees.</p><a href="#support" aria-label="Support the project after reading Forty hands, one courtyard">Join the next chapter <span aria-hidden="true">→</span></a></article><article><div class="update-meta"><time datetime="2026-08-12">12 Aug</time><span>Stewardship</span></div><p class="update-index" aria-hidden="true">01</p><h3>The courtyard is ours to care for</h3><p>Riverbend Library signed the long-term agreement that keeps this space in community hands.</p><a href="#plan" aria-label="Read the Riverbend project plan">See the public plan <span aria-hidden="true">→</span></a></article></div></div>
      </article>

      <aside class="support-card" id="support" aria-labelledby="support-title">
	<div class="funding"><div class="funding-state"><span><span class="live-dot"></span> Community funded</span><span>18 days left</span></div><strong>GHS 182,450</strong><p>raised of GHS 250,000</p><div class="progress" role="progressbar" aria-label="Campaign funding" aria-valuemin="0" aria-valuemax="250000" aria-valuenow="182450"><i></i></div><dl><div><dt>624</dt><dd>supporters</dd></div><div><dt>73%</dt><dd>funded</dd></div><div><dt>3</dt><dd>field notes</dd></div></dl></div>
	<div class="support-impact-promise"><span class="support-impact-mark" aria-hidden="true">✦</span><p><strong>GHS 50 helps stock a growing bed.</strong><span>Seed packs, child-sized tools, and the first planting workshop.</span></p></div>
	<div class="support-form"><p class="chapter-number">Make a contribution</p><h2 id="support-title">Choose how you’ll help it grow.</h2>${setupMessage(error)}<form action="/checkout" method="post" data-contribution-form data-checkout-show-line-items="false"><input type="hidden" name="attempt_id" value="${attemptId}"><fieldset><legend class="sr-only">Contribution amount</legend><label class="tier"><input type="radio" name="tier" value="seed" checked><span><strong>GHS 50</strong><small>Seed the garden</small></span><i>One contribution unit</i></label><label class="tier"><input type="radio" name="tier" value="grower"><span><strong>GHS 100</strong><small>Help it grow</small></span><i>Two contribution units</i></label><label class="tier"><input type="radio" name="tier" value="steward"><span><strong>GHS 250</strong><small>Become a steward</small></span><i>Five contribution units</i></label></fieldset><div class="fields"><label>Full name<input name="name" value="Akua Mensah" autocomplete="name" required></label><label>Email address<input type="email" name="email" value="akua@example.com" autocomplete="email" required></label><label>Phone number<input type="tel" name="phone" value="+233544998605" autocomplete="tel" inputmode="tel" required></label></div>${checkoutPresentationPicker}<p class="checkout-presentation-feedback" data-checkout-feedback aria-live="polite" hidden></p><button type="submit"><span>Contribute GHS 50</span><svg viewBox="0 0 20 20" aria-hidden="true"><path d="m7 4 6 6-6 6"/></svg></button><p class="secure-note"><span aria-hidden="true">◇</span> Secure checkout powered by Inttegro</p></form></div>
	<ul class="support-assurances" aria-label="Campaign assurances"><li><span aria-hidden="true">✓</span><p><strong>Verified organizer</strong><small>Identity and community role reviewed</small></p></li><li><span aria-hidden="true">↗</span><p><strong>Public allocation</strong><small>Milestones and receipts stay visible</small></p></li><li><span aria-hidden="true">◎</span><p><strong>Flexible funding</strong><small>Contributions go directly to the build</small></p></li></ul>
	<footer><p>Openfield collects immediate contributions for this flexible-funding campaign. Contributions are not represented as tax-deductible gifts.</p></footer>
      </aside>
    </section>
    <p class="demo-disclosure">Openfield and Riverbend Foundation are fictional demonstration entities.</p>
  </main>
</div>`);
}

export function resultPage(kind: 'complete' | 'cancel' | 'not-found') {
  const content = kind === 'complete'
    ? { eyebrow: 'Contribution received', title: 'You helped something take root.', copy: 'Openfield will count the contribution only after the server verifies authoritative payment status.', action: 'Return to the garden', mark: '✓', status: 'Verification in progress', next: 'After verification, your contribution joins the next published milestone update.' }
    : kind === 'cancel'
      ? { eyebrow: 'Checkout paused', title: 'Nothing was charged.', copy: 'The garden will be here when you are ready. Your contribution was not marked as complete.', action: 'Choose a contribution', mark: '←', status: 'Contribution not completed', next: 'Your selected contribution remains available when you return to the campaign.' }
      : { eyebrow: 'Page not found', title: 'This path is still unplanted.', copy: 'Return to the Riverbend campaign to see the project and its latest progress.', action: 'Visit the campaign', mark: '↗', status: 'Campaign still active', next: 'The project page has the latest funding total, field evidence, and build milestones.' };
  return document(`<main class="result-page openfield-result-page"><section class="openfield-result"><header class="result-header"><a class="brand" href="/"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16 27V13m0 6c-4.8 0-8-2.7-8-7.5 4.8 0 8 2.7 8 7.5Zm0-3.5c4.8 0 8-2.7 8-7.5-4.8 0-8 2.7-8 7.5Z"/></svg><span>openfield</span></a><span>Riverbend Learning Garden</span></header><div class="result-story"><span class="result-mark">${content.mark}</span><p class="chapter-number">${content.eyebrow}</p><h1>${content.title}</h1><p>${content.copy}</p><a class="result-action" href="/">${content.action}<span>→</span></a></div><aside class="result-impact"><p class="chapter-number">What happens next</p><strong>${content.status}</strong><p>${content.next}</p><dl><div><dt>Campaign progress</dt><dd>73%</dd></div><div><dt>Next milestone</dt><dd>Six more growing beds</dd></div></dl></aside></section></main>`, content.title);
}
